import type { CensusRow, DealershipFlags, SurveyPayload, VisitStatus } from "./types";

/** Public mapping seed for Riyadh's Al Shifa (الشفا) used-car strip.
 *
 * South Riyadh, Al Marwah 14721. Corridors: Ahmad Al Basri, Ibn Sayyidah,
 * Al Khalil Ibn Ahmad. Public directories claim 60+ lots; this file only
 * names lots we can source. No inventory, ASP, FPR, or monthly volume.
 * GPS: five public pins; everything else is corridor-placed and needsGps.
 */
type LatLng = { lat: number; lng: number };

const HARAJ: LatLng = { lat: 24.54852, lng: 46.6805833 };
const CLUSTER: LatLng = { lat: 24.5479261, lng: 46.6818955 };
const YARD: LatLng = { lat: 24.5488603, lng: 46.6804937 };
const SALEH: LatLng = { lat: 24.5515836, lng: 46.6800277 };
const NAJOOM: LatLng = { lat: 24.5510734, lng: 46.6822024 };

function around(base: LatLng, eastM: number, northM: number): LatLng {
  const latM = 111_320;
  const lngM = 111_320 * Math.cos((base.lat * Math.PI) / 180);
  return { lat: +(base.lat + northM / latM).toFixed(7), lng: +(base.lng + eastM / lngM).toFixed(7) };
}

type SeedIn = {
  sdId: string;
  nameEn: string;
  nameAr: string;
  pos: LatLng;
  phone?: string;
  street: string;
  note: string;
  needsGps?: boolean;
  complex?: boolean;
  authorised?: boolean;
  authorisedBrand?: string;
  relatedSdId?: string;
  vehicleType?: SurveyPayload["vehicleType"];
};

function mapsUrl(p: LatLng): string {
  return `https://www.google.com/maps?q=${p.lat},${p.lng}`;
}

function row(s: SeedIn): CensusRow {
  const gpsKnown = s.needsGps === false;
  const flags: DealershipFlags = {
    sdId: s.sdId,
    market: "shifa",
    mappingOnly: true,
    census: false,
    gpsSource: "mapping_seed",
    street: s.street,
    mapsUrl: mapsUrl(s.pos),
    censusVersion: 14,
    needsGps: gpsKnown ? false : true,
    complex: s.complex || undefined,
    authorised: s.authorised || undefined,
    authorisedBrand: s.authorisedBrand || undefined,
    relatedSdId: s.relatedSdId,
  };
  const survey: SurveyPayload = {
    visitDate: "",
    surveyorName: "",
    visitStatus: "not_visited",
    mainBrands: [],
    banksPartnered: [],
    leadOnlinePct: 0,
    authorisedDealer: s.authorised ? "yes" : "",
    authorisedBrand: s.authorisedBrand ?? "",
    vehicleType: s.vehicleType ?? "used_only",
    street: s.street,
    notes: s.note,
  };
  const status: VisitStatus = "not_visited";
  return {
    sdId: s.sdId,
    nameEn: s.nameEn,
    nameAr: s.nameAr,
    lat: s.pos.lat,
    lng: s.pos.lng,
    phone: s.phone ?? "",
    note: s.note,
    status,
    flags,
    survey,
    step: 0,
  };
}

const SEED: SeedIn[] = [
  {
    sdId: "S0001",
    nameEn: "Haraj Al Shifa Used Cars",
    nameAr: "حراج الشفا للسيارات",
    pos: HARAJ,
    phone: "+966539111667",
    street: "6917 Ahmad Al Basri",
    note: "Public GPS. Used-car yard / complex — split lots on site. Phone from public listing. No volumes.",
    needsGps: false,
    complex: true,
  },
  {
    sdId: "S0002",
    nameEn: "Shifa Yard for Used Cars",
    nameAr: "ساحة الشفا للسيارات المستعملة",
    pos: YARD,
    street: "Ahmad Al Basri",
    note: "Public GPS ~40 m from Haraj. Used-car yard. Confirm whether a separate operator or the same complex.",
    needsGps: false,
  },
  {
    sdId: "S0003",
    nameEn: "Al Shifa Car Showrooms (cluster)",
    nameAr: "معارض الشفا للسيارات المعارض",
    pos: CLUSTER,
    phone: "+966550191161",
    street: "6947 Ahmad Al Basri",
    note: "Public GPS. Named cluster of independent lots, not one dealer. Split records while walking.",
    needsGps: false,
    complex: true,
  },
  {
    sdId: "S0004",
    nameEn: "Saleh Group — Al Shifa",
    nameAr: "مجموعة صالح للسيارات — الشفا",
    pos: SALEH,
    phone: "+966920022122",
    street: "7342 Ibn Sayyidah",
    note: "Public GPS. Al Shifa branch. Qadisiyah trained desk is D0309 — do not merge the two sites.",
    needsGps: false,
    relatedSdId: "D0309",
    vehicleType: "mix",
  },
  {
    sdId: "S0005",
    nameEn: "Najoom Al Shifa",
    nameAr: "نجوم الشفا للسيارات",
    pos: NAJOOM,
    phone: "+966540998075",
    street: "Al Khalil Ibn Ahmad",
    note: "Public GPS (plus HM2J+8W). One of the named used-car lots on Al Khalil Ibn Ahmad.",
    needsGps: false,
  },
  {
    sdId: "S0006",
    nameEn: "Afaq Al Shifa",
    nameAr: "أفاق الشفا",
    pos: around(HARAJ, -80, 20),
    street: "6897 Ahmad Al Basri",
    note: "Street-level public listing west of Haraj. Confirm GPS on site.",
  },
  {
    sdId: "S0007",
    nameEn: "Shaibani Cars",
    nameAr: "معرض الشيباني للسيارات",
    pos: around(HARAJ, 40, -25),
    street: "6917 Ahmad Al Basri",
    note: "Listed at the same building number as Haraj. Confirm if a stall inside the yard.",
  },
  {
    sdId: "S0008",
    nameEn: "Rashid Al Damaan Cars",
    nameAr: "معرض راشد ال دمعان للسيارات",
    pos: around(HARAJ, -170, 40),
    street: "6827 Ahmad Al Basri",
    note: "Street-level public listing on Ahmad Al Basri. Confirm GPS on site.",
  },
  {
    sdId: "S0009",
    nameEn: "Sultan Al Rudayyan Cars",
    nameAr: "معرض سلطان الرضيان للسيارات",
    pos: around(CLUSTER, 90, -20),
    street: "7067 Ahmad Al Basri",
    note: "Street-level public listing east of the cluster. Confirm GPS on site.",
  },
  {
    sdId: "S0010",
    nameEn: "Country of Arabism Motor Show",
    nameAr: "معرض بلاد العروبة للسيارات",
    pos: around(HARAJ, -30, -40),
    street: "6917 Ahmad Al Basri",
    note: "Listed at Haraj's building number. Confirm stall vs independent lot.",
  },
  {
    sdId: "S0011",
    nameEn: "Naseem Al Shifa Cars",
    nameAr: "معرض نسيم الشفاء للسيارات",
    pos: around(HARAJ, -140, 10),
    phone: "+966505747734",
    street: "6853 Ahmad Al Basri",
    note: "Public phone + street. Directory also lists 3110 Ahmad Al Basri. Confirm which door.",
  },
  {
    sdId: "S0012",
    nameEn: "Al Shifa New Cars Showroom",
    nameAr: "معرض الشفاء الجديد للسيارات",
    pos: around(NAJOOM, 40, -30),
    phone: "+966505615836",
    street: "Al Khalil Ibn Ahmad",
    note: "Public phone. Directories split the address (Al Khalil vs 7134 Ahmad Al Basri). Confirm door.",
    vehicleType: "mix",
  },
  {
    sdId: "S0013",
    nameEn: "Ahmad Al Basri Marwah Showroom",
    nameAr: "معرض أحمد البصري المروة",
    pos: around(HARAJ, -220, 50),
    phone: "+966564547821",
    street: "3370 Jibril Ibn Jamil",
    note: "Public phone + street off Ahmad Al Basri. Confirm GPS on site.",
  },
  {
    sdId: "S0014",
    nameEn: "Sanaya Shifa",
    nameAr: "سنايا الشفا",
    pos: around(SALEH, 40, -40),
    street: "7129 Ibn Sayyidah",
    note: "Street-level public listing on Ibn Sayyidah. Confirm GPS on site.",
  },
  {
    sdId: "S0015",
    nameEn: "Al Tajweed Showroom",
    nameAr: "معرض التجويد",
    pos: around(SALEH, -50, -50),
    street: "7099 Ibn Sayyidah",
    note: "Street-level public listing. Confirm GPS on site.",
  },
  {
    sdId: "S0016",
    nameEn: "Al Hijaz Cars",
    nameAr: "معرض الحجاز للسيارات",
    pos: around(SALEH, 70, -20),
    street: "7129 Ibn Sayyidah",
    note: "Same building number as Sanaya in some listings. Confirm distinct lot.",
  },
  {
    sdId: "S0017",
    nameEn: "Karaa Cars",
    nameAr: "معرض كراء للسيارات",
    pos: around(SALEH, -80, -80),
    street: "7045 Ibn Sayyidah",
    note: "Street-level public listing. Confirm GPS on site.",
  },
  {
    sdId: "S0018",
    nameEn: "Shalal Najd Cars",
    nameAr: "معرض شلال نجد للسيارات",
    pos: around(SALEH, 20, -90),
    street: "Ibn Sayyidah",
    note: "Street-level public listing. Confirm operator and GPS on site. Qadisiyah desk is D0052 Shalal Najd — do not merge the two sites.",
    relatedSdId: "D0052",
  },
  {
    sdId: "S0019",
    nameEn: "Al Ustoorah 70 Cars",
    nameAr: "معرض شركة الأسطورة (70)",
    pos: around(SALEH, 55, 30),
    street: "7171 Ibn Sayyidah",
    note: "Street-level public listing. Confirm GPS on site.",
  },
  {
    sdId: "S0020",
    nameEn: "Malik Al Jaysh Cars",
    nameAr: "معرض مالك الجيش لبيع وشراء السيارات",
    pos: around(SALEH, 10, 60),
    street: "7225 Ibn Sayyidah",
    note: "Street-level public listing. Confirm GPS on site.",
  },
  {
    sdId: "S0021",
    nameEn: "Al Shifa Showrooms Complex",
    nameAr: "مجمع معارض الشفاء للسيارات",
    pos: around(SALEH, -70, 20),
    phone: "+966555033343",
    street: "Ibn Sayyidah",
    note: "Public phone. Named complex — split individual lots while walking.",
    complex: true,
  },
  {
    sdId: "S0022",
    nameEn: "Al Shenaifi Cars",
    nameAr: "معرض الشنيفي للسيارات",
    pos: around(SALEH, -40, 80),
    phone: "+966599881764",
    street: "7305 Ibn Sayyidah",
    note: "Public phone. Directories also list 3029 Ibn Sayyidah. Confirm door.",
  },
  {
    sdId: "S0023",
    nameEn: "Al Wafi Al Shifa",
    nameAr: "معرض الوافي للسيارات بالشفا",
    pos: around(SALEH, -90, -30),
    phone: "+966500244540",
    street: "7036 Ibn Sayyidah",
    note: "Public phone. Directory also lists 2740 Ibn Sayyidah. Confirm door.",
  },
  {
    sdId: "S0024",
    nameEn: "Ayed Saad Misfer Al Shahrani",
    nameAr: "شركة عايض سعد مسفر الشهراني",
    pos: around(HARAJ, 70, 55),
    street: "Ahmad Al Basri",
    note: "Street-level public listing. Confirm GPS on site.",
  },
  {
    sdId: "S0025",
    nameEn: "Al Sati Cars",
    nameAr: "معرض الصاطي للسيارات",
    pos: around(CLUSTER, -40, 30),
    street: "Ahmad Al Basri / Ibn Sayyidah",
    note: "Public nearby-listing without a building number. Confirm GPS on site.",
  },
  {
    sdId: "S0026",
    nameEn: "Class Cars Al Shifa",
    nameAr: "معرض كلاس للسيارات",
    pos: around(NAJOOM, -20, 20),
    street: "Al Khalil Ibn Ahmad",
    note: "Public nearby-listing ~25 m from Najoom. Confirm GPS on site.",
  },
  {
    sdId: "S0027",
    nameEn: "Alarabah For Cars",
    nameAr: "صالة العربة للسيارات",
    pos: around(NAJOOM, -45, -15),
    street: "3201 Al Khalil Ibn Ahmad",
    note: "Street-level public listing. Confirm GPS on site.",
  },
  {
    sdId: "S0028",
    nameEn: "Al Ibdaa Cars",
    nameAr: "الإبداع للسيارات",
    pos: around(NAJOOM, 55, 25),
    street: "Shari Al Ma'arid, Al Shifa",
    note: "Street-level public listing on Exhibition Street. Confirm GPS on site.",
  },
  {
    sdId: "S0029",
    nameEn: "Khalil Anzi Car Showroom",
    nameAr: "معرض خليل العنزي للسيارات",
    pos: around(NAJOOM, 70, -40),
    street: "3184–3220 Al Khalil Ibn Ahmad",
    note: "Street-level public listing. Confirm GPS on site.",
  },
  {
    sdId: "S0030",
    nameEn: "Al Yamani Cars",
    nameAr: "شركة اليمني للسيارات",
    pos: around(NAJOOM, -60, 40),
    street: "Al Khalil Ibn Ahmad",
    note: "Street-level public listing. Confirm GPS on site.",
  },
  {
    sdId: "S0031",
    nameEn: "Autostar Al Shifa",
    nameAr: "أوتو ستار الشفا",
    pos: around(NAJOOM, 15, 50),
    street: "Al Khalil Ibn Ahmad",
    note: "Street-level public listing. Confirm GPS on site.",
  },
  {
    sdId: "S0032",
    nameEn: "Aljanoub Exhibition",
    nameAr: "معرض الجنوب",
    pos: around(NAJOOM, 80, 15),
    street: "Al Khalil Ibn Ahmad",
    note: "Street-level public listing. Confirm GPS on site.",
  },
  {
    sdId: "S0033",
    nameEn: "Al Janoub Al Hadith",
    nameAr: "معرض الجنوب الحديث للسيارات",
    pos: around(NAJOOM, -70, -35),
    street: "Al Khalil Ibn Ahmad",
    note: "Street-level public listing. Confirm GPS on site.",
  },
  {
    sdId: "S0034",
    nameEn: "Latest Cars — Al Shifa branch",
    nameAr: "أحدث السيارات فرع الشفا",
    pos: around(HARAJ, -200, -80),
    street: "Al Imam Muslim",
    note: "Public listing on Imam Muslim, west of the Ahmad Al Basri strip. Qadisiyah desk is D0180 Latest Cars — confirm same operator on site.",
    relatedSdId: "D0180",
  },
  {
    sdId: "S0035",
    nameEn: "Al Zahrani Cars",
    nameAr: "معرض الزهراني للسيارات",
    pos: around(NAJOOM, 140, -90),
    street: "Masoud Al Umawi",
    note: "Street-level public listing east of the strip. Confirm GPS on site.",
  },
  {
    sdId: "S0036",
    nameEn: "Al Imtiyaz Cars",
    nameAr: "معرض الإمتياز للسيارات",
    pos: around(NAJOOM, 170, -70),
    street: "Masoud Al Umawi",
    note: "Street-level public listing near Al Zahrani. Confirm GPS on site.",
  },
  {
    sdId: "S0037",
    nameEn: "Rawabi Nisah Cars",
    nameAr: "معرض روابي نساح للسيارات",
    pos: around(NAJOOM, 130, 60),
    street: "3214 Abi Abdullah Al Jilani",
    note: "Street-level public listing. Confirm GPS on site.",
  },
  {
    sdId: "S0038",
    nameEn: "Al Fadiliyah",
    nameAr: "معرض الفاضلية",
    pos: around(NAJOOM, 160, 40),
    street: "Abi Al Qasim Al Hussaini",
    note: "Street-level public listing. Confirm GPS on site.",
  },
  {
    sdId: "S0039",
    nameEn: "Alrzeen Auto Show",
    nameAr: "معرض الرزين للسيارات",
    pos: around(NAJOOM, 110, -20),
    street: "3209 Abi Al Ala Al Najmi",
    note: "Named as one of the larger lots in public guides. Confirm GPS — no volumes seeded.",
  },
  {
    sdId: "S0040",
    nameEn: "Misfer Al Shahrani Cars",
    nameAr: "مسفر الشهراني للسيارات",
    pos: around(HARAJ, -250, 30),
    street: "Muhammad Ibn Hamad Abu Shaybah",
    note: "Street-level public listing. Distinct from Ayed Saad Misfer (S0024) until proven otherwise. Qadisiyah desk is D0109.",
    relatedSdId: "D0109",
  },
  {
    sdId: "S0041",
    nameEn: "Bahjat Al Shifa",
    nameAr: "معرض بهجة الشفا للسيارات",
    pos: around(HARAJ, -280, -20),
    phone: "+966536623945",
    street: "3444 Muhammad Ibn Hamad Abu Shaybah",
    note: "Public phone + street. Confirm GPS on site.",
  },
  {
    sdId: "S0042",
    nameEn: "Khaled Cars 2 — Al Shifa",
    nameAr: "خالد للسيارات 2 — فرع الشفا",
    pos: around(HARAJ, -120, -100),
    phone: "+966533717314",
    street: "Al Shifa, Riyadh",
    note: "Public phone (YallaMotor). Address is district-level only — pin to GPS on site. Qadisiyah desk is D0066 Khaled Cars — confirm same operator.",
    relatedSdId: "D0066",
  },
  {
    sdId: "S0043",
    nameEn: "Al Fulaij Auto Sales",
    nameAr: "الفليج لبيع السيارات",
    pos: around(CLUSTER, 50, 80),
    street: "Al Shifa strip",
    note: "Named in public guides as financing-heavy. No address/GPS — corridor placeholder. No volumes.",
  },
  {
    sdId: "S0044",
    nameEn: "Sama Riyadh Showroom",
    nameAr: "معرض سما الرياض",
    pos: around(CLUSTER, -60, 90),
    street: "Al Shifa strip",
    note: "Named in public guides. No address/GPS — corridor placeholder.",
  },
  {
    sdId: "S0045",
    nameEn: "Aljumah Showroom",
    nameAr: "معرض الجمعة",
    pos: around(SALEH, 100, -60),
    street: "Al Shifa strip",
    note: "Named in public guides (used, inspection). No address/GPS — corridor placeholder.",
  },
  {
    sdId: "S0046",
    nameEn: "Masoud Cars",
    nameAr: "معرض مسعود للسيارات",
    pos: around(NAJOOM, 100, -110),
    street: "Al Shifa strip",
    note: "Named in public guides. Distinct from Masoud Al Umawi street lots until proven otherwise.",
  },
  {
    sdId: "S0047",
    nameEn: "Alghamdi Showroom",
    nameAr: "معرض الغامدي",
    pos: around(SALEH, -110, 50),
    street: "Al Shifa strip",
    note: "Named in public guides. No address/GPS — corridor placeholder.",
  },
  {
    sdId: "S0048",
    nameEn: "Al-Yami Showroom",
    nameAr: "معرض اليامي",
    pos: around(HARAJ, 110, 90),
    street: "Al Shifa strip",
    note: "Named in public guides. No address/GPS — corridor placeholder.",
  },
  {
    sdId: "S0049",
    nameEn: "Abdullah Nashban Showroom",
    nameAr: "معرض عبدالله نشبان",
    pos: around(SALEH, 90, 70),
    street: "Al Shifa strip",
    note: "Named in public guides. No address/GPS — corridor placeholder.",
  },
  {
    sdId: "S0050",
    nameEn: "Almultaqa Showroom",
    nameAr: "معرض الملتقى",
    pos: around(NAJOOM, -100, 70),
    street: "Al Shifa strip",
    note: "Named in public guides (Hyundai/Kia mix claimed — unverified). No volumes.",
  },
  {
    sdId: "S0051",
    nameEn: "Sama Najd Showroom",
    nameAr: "معرض سما نجد",
    pos: around(CLUSTER, 120, 40),
    street: "Al Shifa strip",
    note: "Named in public guides. No address/GPS — corridor placeholder.",
  },
  {
    sdId: "S0052",
    nameEn: "Rukn Al Safa Al Mumayaz",
    nameAr: "ركن الصفا المميز للسيارات",
    pos: around(SALEH, -130, -70),
    street: "Al Shifa strip",
    note: "Named in public guides. No address/GPS — corridor placeholder.",
  },
  {
    sdId: "S0053",
    nameEn: "Ramz Al Ikhtiyar — Al Shifa",
    nameAr: "رمز الاختيار — فرع الشفا",
    pos: around(HARAJ, 150, -50),
    phone: "+966532606914",
    street: "Al Shifa strip",
    note: "Public phone. Branch listing — confirm GPS on site.",
  },
  {
    sdId: "S0054",
    nameEn: "Ramz Al Afdaal",
    nameAr: "رمز الأفضل",
    pos: around(HARAJ, 180, 20),
    street: "Al Shifa strip",
    note: "Public used-only listing. Confirm whether distinct from Ramz Al Ikhtiyar.",
  },
  {
    sdId: "S0055",
    nameEn: "Ahad Cars Group — Al Shifa",
    nameAr: "مجموعة أحد — فرع الشفا",
    pos: around(CLUSTER, 80, -70),
    street: "Al Shifa strip",
    note: "Public guides describe this as new/imported — contrast case for a used-car market. No volumes.",
    vehicleType: "new_only",
  },
  {
    sdId: "S0056",
    nameEn: "Al Sari — Al Shifa branch",
    nameAr: "معرض الساري فرع الشفا",
    pos: around(SALEH, 120, 10),
    street: "Al Shifa strip",
    note: "Qadisiyah walked desk is D0146 Al Sari Cars. This is the named Shifa branch — unwalked.",
    relatedSdId: "D0146",
    vehicleType: "mix",
  },
  {
    sdId: "S0057",
    nameEn: "Dar Al Nukhba — Al Shifa",
    nameAr: "دار النخبة للسيارات — الشفا",
    pos: around(SALEH, 150, -40),
    street: "Al Shifa strip",
    note: "Qadisiyah walked desk is D0187 Dar Al Nukhba (new-only, declined induction). Named Shifa branch — unwalked. Confirm used vs mix on site. No volumes.",
    relatedSdId: "D0187",
    vehicleType: "mix",
  },
  {
    sdId: "S0058",
    nameEn: "Mawtin Al Asimah",
    nameAr: "معرض موطن العاصمة",
    pos: around(HARAJ, -60, 70),
    street: "Ahmad Al Basri",
    note: "Named on Haraj as a Shifa used-car seller. No address/GPS — corridor placeholder. No volumes.",
  },
  {
    sdId: "S0059",
    nameEn: "Fal Al Khair Cars",
    nameAr: "معرض فال الخير للسيارات",
    pos: around(NAJOOM, 25, -10),
    street: "Al Khalil Ibn Ahmad",
    note: "Google lists this at the same complex as Al Shifa New Cars (S0012). Confirm distinct stall. No volumes.",
  },
  {
    sdId: "S0060",
    nameEn: "Qimmat Kayan 2",
    nameAr: "معرض قمة كيان 2",
    pos: around(CLUSTER, 30, -50),
    street: "Al Shifa strip",
    note: "Named on Haraj as a Shifa used-car seller. No address/GPS — corridor placeholder. No volumes.",
  },
  {
    sdId: "S0061",
    nameEn: "Rawat Al Muharrikat",
    nameAr: "معرض روعة المحركات للسيارات",
    pos: around(CLUSTER, -90, -40),
    street: "Al Shifa strip",
    note: "Named on Haraj as a Shifa used-car seller. No address/GPS — corridor placeholder. No volumes.",
  },
  {
    sdId: "S0062",
    nameEn: "Durrat Al Shifa",
    nameAr: "درة الشفاء للسيارات",
    pos: around(HARAJ, 90, -70),
    street: "Al Shifa strip",
    note: "Named in public Shifa used-car guides. No address/GPS — corridor placeholder. No volumes.",
  },
  {
    sdId: "S0063",
    nameEn: "Al Aman Cars — Al Shifa",
    nameAr: "الأمان للسيارات — الشفا",
    pos: around(SALEH, -160, 10),
    street: "Al Shifa strip",
    note: "Named in public Shifa used-car guides. No address/GPS — corridor placeholder. No volumes.",
  },
  {
    sdId: "S0064",
    nameEn: "Al Badr Cars — Al Shifa",
    nameAr: "معرض البدر للسيارات — الشفا",
    pos: around(NAJOOM, -90, -60),
    street: "Al Shifa strip",
    note: "Named in public Shifa used-car guides. No address/GPS — corridor placeholder. No volumes.",
  },
  {
    sdId: "S0065",
    nameEn: "Al Faris Cars — Al Shifa",
    nameAr: "الفارس للسيارات — الشفا",
    pos: around(SALEH, 80, 90),
    street: "Al Shifa strip",
    note: "Named in public Shifa used-car guides. No address/GPS — corridor placeholder. No volumes.",
  },
  {
    sdId: "S0066",
    nameEn: "Rukn Al Shifa",
    nameAr: "ركن الشفاء للسيارات",
    pos: around(HARAJ, -90, -60),
    street: "Al Shifa strip",
    note: "Named in public Shifa used-car guides. Distinct from Rukn Al Safa (S0052) until proven otherwise. No volumes.",
  },
  {
    sdId: "S0067",
    nameEn: "Al Mutamayyiz — Al Shifa",
    nameAr: "المتميز للسيارات — الشفا",
    pos: around(CLUSTER, 160, -20),
    street: "Al Shifa strip",
    note: "Named in public Shifa used-car guides. No address/GPS — corridor placeholder. No volumes.",
  },
];

export const SHIFA_ROWS: CensusRow[] = SEED.map(row);
export const SHIFA_COUNT = SHIFA_ROWS.length;
