import type { SurveyPayload, VisitStatus } from "./types";

export type OctDoor = {
  sdId: string;
  nameEn: string;
  nameAr: string;
  lat: number;
  lng: number;
  phone?: string;
  mapsUrl?: string;
  status?: VisitStatus;
  note: string;
  survey: Partial<SurveyPayload>;
};

export const SHIFA_FLOOR_OCT01: OctDoor[] = [
  { sdId: "S14WRD", nameEn: "Warid Al Tamayuz", nameAr: "معرض وارد التميز", lat: 24.5455418, lng: 46.6844734, phone: "0574777773", mapsUrl: "https://maps.app.goo.gl/7MGYPpyBkUh3PSg4A", note: "New and used mix. One of the few new-car desks in Al Shifa. Nissan Patrol 2026 is the dense row. 1000 m2.", survey: { vehicleType: "mix", inventoryUnits: 40, showroomSizeSqm: 1000, avgSellingPriceSar: 130000, mainBrands: ["Nissan Patrol", "Honda", "Jetour", "Changan", "Hyundai"] } },
  { sdId: "S14TMZ", nameEn: "Tamayuz Al Shifa", nameAr: "معرض تميز الشفاء", lat: 24.5455794, lng: 46.6845573, note: "Used only. Old Mercedes, Ford, Chevrolet, Hyundai, and a few commercials. 90% over 5 years.", survey: { vehicleType: "used_only", inventoryUnits: 35, inventoryAgePctOver5: 90, avgSellingPriceSar: 50000, mainBrands: ["Mercedes", "Ford", "Chevrolet", "Hyundai"] } },
  { sdId: "S14TWR", nameEn: "Al Tawra Cars", nameAr: "معرض التوره", lat: 24.5453416, lng: 46.6850374, phone: "0552077779", mapsUrl: "https://maps.app.goo.gl/xiUEQgT28tGtZu7q8", note: "Used only. Hyundai, Ford, Chevrolet, Hilux, Toyota. 90% over 5 years. 1000 m2. MARK: check this is not the same door as S0118 Turo 1.", survey: { vehicleType: "used_only", inventoryUnits: 45, showroomSizeSqm: 1000, inventoryAgePctOver5: 90, avgSellingPriceSar: 35000, mainBrands: ["Hyundai", "Ford", "Chevrolet", "Toyota Hilux", "Toyota"] } },
  { sdId: "S14SHM", nameEn: "Shumukh Al Sharq Cars", nameAr: "معرض شموخ الشرق للسيارات", lat: 24.5454282, lng: 46.6841462, phone: "0542039378", mapsUrl: "https://maps.app.goo.gl/cXWKPAJVeh89Xfpy8", note: "Old and new mix. Premium used row. 16 units outside. 1200 m2. 30% over 5 years.", survey: { vehicleType: "mix", inventoryUnits: 80, inventoryOutside: 16, inventoryInside: 64, showroomSizeSqm: 1200, inventoryAgePctOver5: 30, avgSellingPriceSar: 170000, mainBrands: ["Mercedes", "BMW", "Lexus", "Jeep Rubicon", "Range Rover", "Cadillac Escalade", "Audi", "Toyota", "Ford"] } },
  { sdId: "S14MSR", nameEn: "Al Masari Cars", nameAr: "معرض المسعري للسيارات", lat: 24.5451093, lng: 46.6853671, phone: "0508716258", mapsUrl: "https://maps.app.goo.gl/mq8Rb1gafFg2oE1Q8", note: "Commercial only. Used freezer Isuzu 7-ton Dyna and Isuzu Super Jumbo. 900 m2. 90% over 5 years.", survey: { vehicleType: "commercial", inventoryUnits: 50, showroomSizeSqm: 900, inventoryAgePctOver5: 90, mainBrands: ["Isuzu Dyna", "Isuzu Super Jumbo"] } },
  { sdId: "S14APK", nameEn: "Auto Park Cars", nameAr: "معرض اوتو بارك للسيارات", lat: 24.5447568, lng: 46.6860129, mapsUrl: "https://maps.app.goo.gl/W1zKkS4YoDrkCy3h9", note: "Premium used only. 1400 m2. 40% over 5 years.", survey: { vehicleType: "used_only", inventoryUnits: 50, showroomSizeSqm: 1400, inventoryAgePctOver5: 40, avgSellingPriceSar: 150000, mainBrands: ["Mercedes", "Audi", "BMW", "GMC", "Kia", "Range Rover"] } },
  { sdId: "S14MTN", nameEn: "Mawtin Al Asimah Exhibition", nameAr: "معرض موطن العاصمة للسيارات", lat: 24.5445675, lng: 46.6862542, note: "Used only. 800 m2. 70% over 5 years. Pin is the surveyor coordinate.", survey: { vehicleType: "used_only", inventoryUnits: 40, showroomSizeSqm: 800, inventoryAgePctOver5: 70, avgSellingPriceSar: 40000, mainBrands: ["Hyundai", "Kia", "Toyota", "Chevrolet", "Peugeot", "MG"] } },
  { sdId: "S14HMD", nameEn: "Al Hammad Cars", nameAr: "معرض الحماد للسيارات", lat: 24.5443439, lng: 46.6861992, status: "closed", note: "CLOSED on the 1 Oct walk. Pin is the surveyor coordinate.", survey: { visitStatus: "closed" } },
  { sdId: "S14FNS", nameEn: "Faisal Nasser Al Mutairi", nameAr: "معرض فيصل ناصر المطيري", lat: 24.5451144, lng: 46.6842697, mapsUrl: "https://maps.app.goo.gl/u9wh5QWY1yse8rfh7", note: "Used sedans only. 800 m2. 90% over 5 years.", survey: { vehicleType: "used_only", inventoryUnits: 35, showroomSizeSqm: 800, inventoryAgePctOver5: 90, avgSellingPriceSar: 40000, mainBrands: ["Toyota", "Geely", "Ford", "Hyundai", "Honda"] } },
  { sdId: "S14SND", nameEn: "Al Sunaid Cars", nameAr: "السنيد للسيارات", lat: 24.5446703, lng: 46.6841637, note: "Premium used. Double warehouse, 2500 m2. High density of Jeep Sahara and Rubicon. 49% over 5 years.", survey: { vehicleType: "used_only", inventoryUnits: 80, showroomSizeSqm: 2500, inventoryAgePctOver5: 49, avgSellingPriceSar: 200000, mainBrands: ["Jeep Sahara", "Jeep Rubicon", "Genesis", "Hyundai", "BMW", "GMC", "Cadillac Escalade", "Ford", "Chevrolet", "Porsche", "Mercedes"] } },
  { sdId: "S14SHH", nameEn: "Shihana Cars", nameAr: "معرض شيهانة للسيارات", lat: 24.5451783, lng: 46.6843454, mapsUrl: "https://maps.app.goo.gl/9RR5FukoZvizmpTV9", note: "Used only. Mostly SUV. Also written as معرض مركبه شيهانته. 800 m2. 80% over 5 years.", survey: { vehicleType: "used_only", inventoryUnits: 25, showroomSizeSqm: 800, inventoryAgePctOver5: 80, avgSellingPriceSar: 50000, mainBrands: ["Toyota Hilux", "GMC", "Chevrolet", "Hyundai Creta"] } },
  { sdId: "S14MDC", nameEn: "Mada Car", nameAr: "معرض مدى كار للسيارات", lat: 24.545765, lng: 46.6836374, mapsUrl: "https://maps.app.goo.gl/qhz62TadcvyoyRhM7", note: "Premium used. High quantity of Range Rover. 1400 m2. 60% over 5 years.", survey: { vehicleType: "used_only", inventoryUnits: 40, showroomSizeSqm: 1400, inventoryAgePctOver5: 60, avgSellingPriceSar: 100000, mainBrands: ["Mercedes", "Range Rover", "Toyota Camry", "Mazda", "GMC", "Lexus"] } },
  { sdId: "S14AJY", nameEn: "Ajyal Cars", nameAr: "معرض أجيال السيارات", lat: 24.5460633, lng: 46.6837652, mapsUrl: "https://maps.app.goo.gl/UwzwUczte9vpAqHX8", note: "Used only. Mid segment mix. 1400 m2. 70% over 5 years.", survey: { vehicleType: "used_only", inventoryUnits: 60, showroomSizeSqm: 1400, inventoryAgePctOver5: 70, avgSellingPriceSar: 55000, mainBrands: ["Hyundai", "Kia", "Genesis", "Toyota", "Changan", "Hyundai Creta", "Mazda", "Haval", "Honda"] } },
  { sdId: "S14ZWY", nameEn: "Zawiyat Al Tamlik", nameAr: "زاوية التمليك للسيارات", lat: 24.5463584, lng: 46.6831529, mapsUrl: "https://maps.app.goo.gl/cPfamyAj76HyadKj7", note: "Mostly SUV. Premium units. 1000 m2. ASP not taken.", survey: { vehicleType: "used_only", inventoryUnits: 40, showroomSizeSqm: 1000, mainBrands: ["Lexus", "GMC", "Jeep", "Chevrolet", "Jetour", "Dodge Charger", "Toyota"] } },
  { sdId: "S14ARB", nameEn: "Al Araba Al Sagheera", nameAr: "معرض العربة الصغيرة للسيارات", lat: 24.5458728, lng: 46.6832226, mapsUrl: "https://maps.app.goo.gl/StghoQeeWJcxVFsp8", note: "New and used mix, mostly new. All banks present.", survey: { vehicleType: "mix", inventoryUnits: 65, avgSellingPriceSar: 105000, financeAvailable: "yes", financeEvidence: "All banks on the floor.", mainBrands: ["Toyota Hilux", "Changan", "Hyundai Sonata", "Hyundai Elantra", "Hyundai Accent", "Kia", "Hyundai Creta", "Jaecoo"] } },
  { sdId: "S14MWJ", nameEn: "Mawj Al Shifa Cars", nameAr: "معرض موج الشفا للسيارات", lat: 24.5458686, lng: 46.6826608, mapsUrl: "https://maps.app.goo.gl/u8vPFxM2qBuaGYBV9", note: "Used only, economy to upper mid. High quantity of Kia Pegas. 1200 m2. 40% over 5 years. Finance on used cars.", survey: { vehicleType: "used_only", inventoryUnits: 80, showroomSizeSqm: 1200, inventoryAgePctOver5: 40, avgSellingPriceSar: 60000, financeAvailable: "yes", financeEvidence: "All finance facilities on used cars.", mainBrands: ["Hyundai", "Toyota", "Kia", "Kia Pegas"] } },
  { sdId: "S14AMD", nameEn: "Ali Othman Ahmed Al Amudi", nameAr: "معرض علي عثمان أحمد العمودي للسيارات", lat: 24.5453476, lng: 46.6826932, mapsUrl: "https://maps.app.goo.gl/mRTvhMY6wwVZsgDP6", note: "Hilux and Land Cruiser desert only. 700 m2. 65% over 5 years.", survey: { vehicleType: "used_only", inventoryUnits: 30, showroomSizeSqm: 700, inventoryAgePctOver5: 65, avgSellingPriceSar: 80000, mainBrands: ["Toyota Hilux", "Toyota Land Cruiser"] } },
  { sdId: "S14SBR", nameEn: "Al Saber Cars Al Shifa", nameAr: "شركة السبر للسيارات الشفا", lat: 24.5448365, lng: 46.6832997, mapsUrl: "https://maps.app.goo.gl/cKtUZ79B4XTryRYS7", note: "Mostly commercial project-white floor: Citroen van, Tata pickup, Ashok Leyland. A few Audi and BMW. 90 units. 2500 m2. 5% over 5 years. All banks present.", survey: { vehicleType: "mix", inventoryUnits: 90, showroomSizeSqm: 2500, inventoryAgePctOver5: 5, avgSellingPriceSar: 90000, financeAvailable: "yes", financeEvidence: "All banks present.", mainBrands: ["Citroen", "Tata", "Ashok Leyland", "Audi", "BMW"] } },
  { sdId: "S14HDY", nameEn: "Al Hadyan", nameAr: "معرض الهديان", lat: 24.5447342, lng: 46.6826904, mapsUrl: "https://maps.app.goo.gl/BmvANs4M1fg465CF8", note: "35 units on the floor. Brands, ASP and age not taken.", survey: { inventoryUnits: 35 } },
];
