import type { ShifaSeedIn } from "./shifa-walk-sep20-types";

/** 20 Sep 2026 Al Shifa walk — part A (S0085–S0099).
 *
 * Source: surveyor's GROK_LINKS field sheet (122 showrooms), merged 20 Sep 2026.
 * Positions are metre offsets from the CLUSTER anchor used across census.ts.
 *
 * GPS provenance is stated per record in `note`:
 *   - pins resolved against Google Places carry a mapsUrl and an exact/variant note
 *   - records marked "NO GPS" keep the surveyor's nearby placeholder coordinate
 *     and still need an on-site tap. Do not treat those pins as surveyed locations.
 *
 * Inventory, size, ASP and brand values are the surveyor's own floor figures.
 * financeAvailable is "unknown" throughout — the sheet did not record it.
 */
export const SHIFA_WALK_SEP20_A: ShifaSeedIn[] = [
  {
    sdId: "S0085",
    nameEn: "Barakat Al Markabat Cars",
    nameAr: "معرض بركة المركبات للسيارات",
    pos: { eastM: 233.3, northM: -58.6 },
    street: "Al Shifa strip",
    note: "Al Shifa walk 20 Sep 2026. NO GPS — coordinate is the surveyor's nearby placeholder, not a real pin. Needs a tap on site.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 45,
      inventoryInside: 18,
      inventoryOutside: 6,
      inventoryAgePctOver5: 10,
      showroomSizeSqm: 700,
      mainBrands: ["Chrysler", "GMC", "Jetour", "Mercedes", "Mazda"],
      avgSellingPriceSar: 100000,
      financeAvailable: "unknown",
      vehicleType: "used_only",
    },
  },
  {
    sdId: "S0086",
    nameEn: "Walid Cars — Al Shifa",
    nameAr: "وليد السيارات",
    pos: { eastM: 223.2, northM: -125.4 },
    street: "Al Shifa strip",
    note: "Al Shifa walk 20 Sep 2026. NO GPS — coordinate is the surveyor's nearby placeholder, not a real pin. Needs a tap on site.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 30,
      inventoryAgePctOver5: 80,
      showroomSizeSqm: 800,
      mainBrands: ["Ford", "GMC", "Land Rover", "Toyota"],
      avgSellingPriceSar: 70000,
      financeAvailable: "unknown",
      vehicleType: "used_only",
    },
  },
  {
    sdId: "S0087",
    nameEn: "Saeed Salem Al Shahrani Cars Co.",
    nameAr: "شركة سعيد سالم الشهراني للسيارات",
    pos: { eastM: -220.1, northM: 258.7 },
    street: "Ibn Sayyidah",
    mapsUrl: "https://www.google.com/maps?q=24.55025,46.6797222",
    note: "Al Shifa walk 20 Sep 2026. GPS pin resolved from Google Places (exact name match) — confirm on site.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 45,
      inventoryAgePctOver5: 0,
      showroomSizeSqm: 800,
      mainBrands: ["Ford", "Hyundai"],
      avgSellingPriceSar: 100000,
      financeAvailable: "unknown",
      vehicleType: "new_only",
    },
  },
  {
    sdId: "S0088",
    nameEn: "Adwaa Suwaidan Cars (Yousef Mubarak)",
    nameAr: "معرض اضواء سويدان للسيارات لصاحبه يوسف مبارك",
    pos: { eastM: -322.7, northM: 295.1 },
    street: "Abdulwahab Ibn Sulaiman",
    mapsUrl: "https://www.google.com/maps?q=24.550577,46.6787088",
    note: "Al Shifa walk 20 Sep 2026. GPS pin resolved from Google Places (exact name match) — confirm on site.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 50,
      inventoryAgePctOver5: 60,
      showroomSizeSqm: 500,
      mainBrands: ["GMC", "Hyundai"],
      avgSellingPriceSar: 70000,
      financeAvailable: "unknown",
      vehicleType: "mix",
    },
  },
  {
    sdId: "S0089",
    nameEn: "Saed Al Malki Cars",
    nameAr: "معرض ساعد المالكي للسيارات",
    pos: { eastM: -67.2, northM: 276.0 },
    street: "Al Shifa strip",
    mapsUrl: "https://www.google.com/maps?q=24.5504053,46.6812317",
    note: "Al Shifa walk 20 Sep 2026. GPS pin resolved from Google Places (exact name match) — confirm on site.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 40,
      inventoryAgePctOver5: 60,
      showroomSizeSqm: 500,
      mainBrands: ["Hyundai", "Kia", "Toyota", "Ford", "Chevrolet", "MG", "Geely", "Changan", "Bestune", "Lexus"],
      avgSellingPriceSar: 55000,
      financeAvailable: "unknown",
      vehicleType: "used_only",
    },
  },
  {
    sdId: "S0090",
    nameEn: "Isnad Al Fiddiyah Ltd",
    nameAr: "شركة اسناد الفضية المحدوده",
    pos: { eastM: -278.5, northM: 274.2 },
    street: "Ash Shifa",
    mapsUrl: "https://www.google.com/maps?q=24.5503897,46.6791455",
    note: "Al Shifa walk 20 Sep 2026. GPS pin resolved from Google Places (exact name match) — confirm on site.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 150,
      inventoryAgePctOver5: 15,
      showroomSizeSqm: 1200,
      mainBrands: ["Hyundai", "Nissan", "Changan"],
      avgSellingPriceSar: 50000,
      financeAvailable: "unknown",
      vehicleType: "used_only",
    },
  },
  {
    sdId: "S0091",
    nameEn: "Al Nisawi Cars",
    nameAr: "النساوي للسيارات",
    pos: { eastM: 152.3, northM: -80.8 },
    street: "Al Shifa strip",
    note: "Al Shifa walk 20 Sep 2026. NO GPS — coordinate is the surveyor's nearby placeholder, not a real pin. Needs a tap on site.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 20,
      inventoryAgePctOver5: 50,
      showroomSizeSqm: 400,
      mainBrands: ["Hyundai", "Toyota"],
      avgSellingPriceSar: 40000,
      financeAvailable: "unknown",
      vehicleType: "used_only",
    },
  },
  {
    sdId: "S0092",
    nameEn: "Qimmat Al Wafi Cars",
    nameAr: "معرض قمة الوافي للسيارات",
    pos: { eastM: 970.0, northM: 15.0 },
    street: "Al Shifa strip",
    note: "Al Shifa walk 20 Sep 2026. NO GPS — coordinate is the surveyor's nearby placeholder, not a real pin. Needs a tap on site.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 80,
      inventoryInside: 80,
      inventoryOutside: 0,
      inventoryAgePctOver5: 0,
      showroomSizeSqm: 1000,
      mainBrands: ["Isuzu"],
      avgSellingPriceSar: 105000,
      financeAvailable: "unknown",
      vehicleType: "new_only",
    },
  },
  {
    sdId: "S0093",
    nameEn: "Riyada Cars",
    nameAr: "رياضة كارز",
    pos: { eastM: 243.5, northM: 97.3 },
    street: "Al Shifa strip",
    note: "Al Shifa walk 20 Sep 2026. NO GPS — coordinate is the surveyor's nearby placeholder, not a real pin. Needs a tap on site.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 50,
      inventoryAgePctOver5: 0,
      showroomSizeSqm: 700,
      mainBrands: ["Jetour", "Mercedes", "Hyundai", "Kia", "Dodge"],
      avgSellingPriceSar: 110000,
      financeAvailable: "unknown",
      vehicleType: "mix",
    },
  },
  {
    sdId: "S0094",
    nameEn: "Ramz Al Riyadh 2",
    nameAr: "شركة رمز الرياض2",
    pos: { eastM: -329.1, northM: 136.1 },
    street: "Ibn Sayyidah",
    mapsUrl: "https://www.google.com/maps?q=24.5491491,46.6786454",
    note: "Al Shifa walk 20 Sep 2026. GPS pin resolved from Google Places (exact name match) — confirm on site.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 65,
      inventoryAgePctOver5: 60,
      showroomSizeSqm: 800,
      mainBrands: ["Kia", "Hyundai", "Changan", "Toyota", "Ford"],
      avgSellingPriceSar: 55000,
      financeAvailable: "unknown",
      vehicleType: "used_only",
    },
  },
  {
    sdId: "S0095",
    nameEn: "Wisam Al Majd Cars Al Shifa 2",
    nameAr: "شركة وسام المجد للسيارات الشفا 2",
    pos: { eastM: -189.9, northM: 396.2 },
    street: "Ibn Sayyidah",
    mapsUrl: "https://www.google.com/maps?q=24.5514848,46.6800203",
    note: "Al Shifa walk 20 Sep 2026. GPS pin resolved from Google Places (exact name match) — confirm on site.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 110,
      inventoryInside: 100,
      inventoryOutside: 10,
      inventoryAgePctOver5: 0,
      showroomSizeSqm: 1200,
      mainBrands: ["Lexus", "Chevrolet", "Jetour", "MG", "Toyota"],
      avgSellingPriceSar: 120000,
      financeAvailable: "unknown",
      vehicleType: "new_only",
    },
  },
  {
    sdId: "S0096",
    nameEn: "Road Lights Modern for Cars",
    nameAr: "معرض رود لايتس مودرن للسيارات",
    pos: { eastM: 192.8, northM: 75.0 },
    street: "Al Shifa strip",
    note: "Al Shifa walk 20 Sep 2026. NO GPS — coordinate is the surveyor's nearby placeholder, not a real pin. Needs a tap on site.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 35,
      inventoryAgePctOver5: 10,
      showroomSizeSqm: 500,
      mainBrands: ["Lexus", "Nissan", "Kia", "Honda", "GMC"],
      avgSellingPriceSar: 100000,
      financeAvailable: "unknown",
      vehicleType: "used_only",
    },
  },
  {
    sdId: "S0097",
    nameEn: "Al Zabadani Cars",
    nameAr: "معرض الزبداني للسيارات",
    pos: { eastM: -80.8, northM: 412.4 },
    street: "Al Khalil Ibn Ahmad",
    mapsUrl: "https://www.google.com/maps?q=24.5516309,46.6810979",
    note: "Al Shifa walk 20 Sep 2026. GPS pin resolved from Google Places (exact name match) — confirm on site.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 70,
      inventoryAgePctOver5: 50,
      showroomSizeSqm: 800,
      mainBrands: ["Lexus", "Toyota", "Genesis"],
      avgSellingPriceSar: 95000,
      financeAvailable: "unknown",
      vehicleType: "used_only",
    },
  },
  {
    sdId: "S0098",
    nameEn: "Al Adeeni Cars",
    nameAr: "معرض العديني للسيارات",
    pos: { eastM: -409.9, northM: 75.9 },
    street: "Ibn Sayyidah",
    mapsUrl: "https://www.google.com/maps?q=24.5486083,46.6778478",
    note: "Al Shifa walk 20 Sep 2026. GPS pin resolved from Google Places (exact name match) — confirm on site.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 50,
      inventoryAgePctOver5: 0,
      showroomSizeSqm: 800,
      mainBrands: ["Mercedes", "BMW", "Lexus", "Jetour"],
      avgSellingPriceSar: 160000,
      financeAvailable: "unknown",
      vehicleType: "used_only",
    },
  },
  {
    sdId: "S0099",
    nameEn: "Abu Ghazi Cars (Mohammed Musleh Al Sufyani)",
    nameAr: "معرض ابوغازى للسيارات (محمد مصلح الصفياني)",
    pos: { eastM: -407.0, northM: 73.8 },
    street: "Ubaidullah Ibn Abi Al Maali",
    mapsUrl: "https://www.google.com/maps?q=24.5485895,46.6778758",
    note: "Al Shifa walk 20 Sep 2026. GPS pin resolved from Google Places (exact name match) — confirm on site.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 60,
      inventoryAgePctOver5: 40,
      showroomSizeSqm: 1000,
      mainBrands: ["Mercedes", "BMW", "Lexus", "Toyota"],
      avgSellingPriceSar: 100000,
      financeAvailable: "unknown",
      vehicleType: "used_only",
    },
  },
];
