import type { ShifaSeedIn } from "./shifa-walk-sep20-types";

/** 20 Sep 2026 Al Shifa walk — part B (S0100–S0113).
 *
 * Source: surveyor's GROK_LINKS field sheet (122 showrooms), merged 20 Sep 2026.
 * Positions are metre offsets from the CLUSTER anchor used across census.ts.
 *
 * GPS provenance is stated per record in `note`:
 *   - pins resolved against Google Places carry a mapsUrl and an exact/variant note
 *   - records marked "NO GPS" keep the surveyor's nearby placeholder coordinate
 *     and still need an on-site tap. Do not treat those pins as surveyed locations.
 *
 * Inventory, size, ASP and brand values are the surveyor's own floor figures.
 * financeAvailable is "unknown" throughout — the sheet did not record it.
 */
export const SHIFA_WALK_SEP20_B: ShifaSeedIn[] = [
  {
    sdId: "S0100",
    nameEn: "Mubarak Cars Al Shifa",
    nameAr: "معرض مبارك للسيارات الشفا",
    pos: { eastM: -117.5, northM: 408.3 },
    street: "Ibn Sayyidah",
    mapsUrl: "https://www.google.com/maps?q=24.5515935,46.6807347",
    note: "Al Shifa walk 20 Sep 2026. GPS pin resolved from Google Places (exact name match) — confirm on site.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 70,
      inventoryAgePctOver5: 20,
      showroomSizeSqm: 800,
      mainBrands: ["Mercedes", "Lexus", "Ford", "Hyundai", "Kia", "Toyota"],
      avgSellingPriceSar: 85000,
      financeAvailable: "unknown",
      vehicleType: "mix",
    },
  },
  {
    sdId: "S0101",
    nameEn: "Sama Dirab Cars",
    nameAr: "معرض سماء ديراب للسيارات",
    pos: { eastM: 172.6, northM: -92.0 },
    street: "Al Shifa strip",
    note: "Al Shifa walk 20 Sep 2026. NO GPS — coordinate is the surveyor's nearby placeholder, not a real pin. Needs a tap on site.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 35,
      inventoryInside: 20,
      inventoryOutside: 2,
      inventoryAgePctOver5: 60,
      showroomSizeSqm: 450,
      mainBrands: ["Nissan", "Mazda", "Toyota", "Honda", "Hyundai", "Lexus"],
      avgSellingPriceSar: 38000,
      financeAvailable: "unknown",
      vehicleType: "used_only",
    },
  },
  {
    sdId: "S0102",
    nameEn: "Saad Mohammed Al Qahtani Cars",
    nameAr: "معرض سعد محمد القحطاني للسيارات",
    pos: { eastM: 253.6, northM: -158.8 },
    street: "Al Shifa strip",
    note: "Al Shifa walk 20 Sep 2026. NO GPS — coordinate is the surveyor's nearby placeholder, not a real pin. Needs a tap on site.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 50,
      inventoryAgePctOver5: 15,
      showroomSizeSqm: 800,
      mainBrands: ["Suzuki", "Toyota", "Nissan", "Hyundai", "Kia"],
      avgSellingPriceSar: 40000,
      financeAvailable: "unknown",
      vehicleType: "used_only",
    },
  },
  {
    sdId: "S0103",
    nameEn: "Al Duhaim Cars",
    nameAr: "الدحيم للسيارات",
    pos: { eastM: -195.6, northM: 308.3 },
    street: "Al Marwah",
    mapsUrl: "https://www.google.com/maps?q=24.550696,46.6799638",
    note: "Al Shifa walk 20 Sep 2026. GPS pin resolved from Google Places (exact name match) — confirm on site.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 70,
      inventoryInside: 60,
      inventoryOutside: 10,
      inventoryAgePctOver5: 30,
      showroomSizeSqm: 1000,
      mainBrands: ["Toyota", "Chevrolet", "GMC", "Ford", "Honda", "Nissan", "MG"],
      avgSellingPriceSar: 100000,
      financeAvailable: "unknown",
      vehicleType: "used_only",
    },
  },
  {
    sdId: "S0104",
    nameEn: "Nojoom Al Etimad Cars",
    nameAr: "نجوم الاعتماد للسيارات",
    pos: { eastM: -457.8, northM: 708.0 },
    street: "Al Khalil Ibn Ahmad",
    mapsUrl: "https://www.google.com/maps?q=24.5542865,46.677374",
    note: "Al Shifa walk 20 Sep 2026. GPS pin resolved from Google Places (exact name match) but sits ~700 m north of the main Al Shifa strip — VERIFY on site before routing.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 20,
      inventoryAgePctOver5: 10,
      showroomSizeSqm: 400,
      mainBrands: ["Toyota", "Ford"],
      avgSellingPriceSar: 90000,
      financeAvailable: "unknown",
      vehicleType: "mix",
    },
  },
  {
    sdId: "S0105",
    nameEn: "Al Ghuraybi Cars",
    nameAr: "معرض الغريبي للسيارات",
    pos: { eastM: 132.1, northM: -147.6 },
    street: "Al Shifa strip",
    note: "Al Shifa walk 20 Sep 2026. NO GPS — coordinate is the surveyor's nearby placeholder, not a real pin. Needs a tap on site.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 25,
      inventoryAgePctOver5: 100,
      showroomSizeSqm: 400,
      mainBrands: ["Toyota", "GMC"],
      avgSellingPriceSar: 25000,
      financeAvailable: "unknown",
      vehicleType: "used_only",
    },
  },
  {
    sdId: "S0106",
    nameEn: "Rawaat Al Saha Cars",
    nameAr: "معرض روعة الساحة للسيارات",
    pos: { eastM: -223.0, northM: 317.2 },
    street: "Ibn Sayyidah",
    mapsUrl: "https://www.google.com/maps?q=24.5507751,46.6796929",
    note: "Al Shifa walk 20 Sep 2026. GPS pin resolved from Google Places (exact name match) — confirm on site.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 76,
      inventoryInside: 65,
      inventoryOutside: 11,
      inventoryAgePctOver5: 25,
      showroomSizeSqm: 1000,
      mainBrands: ["Toyota", "Honda", "Hyundai"],
      avgSellingPriceSar: 78000,
      financeAvailable: "unknown",
      vehicleType: "used_only",
    },
  },
  {
    sdId: "S0107",
    nameEn: "Saad Muhaysin Al Otaibi Cars",
    nameAr: "معرض سعد محيسن العتيبي للسيارات",
    pos: { eastM: -130.9, northM: 292.1 },
    street: "Al Imam Muslim",
    mapsUrl: "https://www.google.com/maps?q=24.5505499,46.6806026",
    note: "Al Shifa walk 20 Sep 2026. GPS pin resolved from Google Places (exact name match) — confirm on site.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 45,
      inventoryAgePctOver5: 45,
      showroomSizeSqm: 600,
      mainBrands: ["Toyota", "Hyundai", "Kia", "Ford", "Nissan", "Chevrolet", "GMC", "Jeep", "Lexus"],
      avgSellingPriceSar: 75000,
      financeAvailable: "unknown",
      vehicleType: "used_only",
    },
  },
  {
    sdId: "S0108",
    nameEn: "Al Mahdani Cars",
    nameAr: "معرض المهداني للسيارات",
    pos: { eastM: 21.7, northM: 190.2 },
    street: "Ash Shifa",
    mapsUrl: "https://www.google.com/maps?q=24.5496349,46.6821094",
    note: "Al Shifa walk 20 Sep 2026. GPS pin resolved from Google Places (exact name match) — confirm on site.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 35,
      inventoryAgePctOver5: 55,
      showroomSizeSqm: 450,
      mainBrands: ["Toyota", "Hyundai", "Kia", "Nissan", "Ford"],
      avgSellingPriceSar: 55000,
      financeAvailable: "unknown",
      vehicleType: "used_only",
    },
  },
  {
    sdId: "S0109",
    nameEn: "Al Jubail for Cars",
    nameAr: "الجبيل للسيارات",
    pos: { eastM: -274.2, northM: 337.3 },
    street: "Al Marwah",
    mapsUrl: "https://www.google.com/maps?q=24.5509565,46.6791872",
    note: "Al Shifa walk 20 Sep 2026. GPS pin resolved from Google Places under a name variant (\\\"Ibn Al Jubail, Al Shifa branch\\\") — VERIFY identity on site.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 120,
      inventoryAgePctOver5: 5,
      showroomSizeSqm: 1000,
      mainBrands: ["Toyota", "Hyundai", "Nissan"],
      avgSellingPriceSar: 100000,
      financeAvailable: "unknown",
      vehicleType: "mix",
    },
  },
  {
    sdId: "S0110",
    nameEn: "Al Harthi Cars (buy & sell)",
    nameAr: "معرض الحارثي لبيع وشراء السيارات",
    pos: { eastM: -467.1, northM: -14.0 },
    street: "Al Imam Muslim",
    mapsUrl: "https://www.google.com/maps?q=24.5478001,46.6772823",
    note: "Al Shifa walk 20 Sep 2026. GPS pin resolved from Google Places on a partial name match — VERIFY identity on site.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 100,
      inventoryInside: 90,
      inventoryOutside: 8,
      inventoryAgePctOver5: 45,
      showroomSizeSqm: 1000,
      mainBrands: ["Toyota", "Lexus", "Chevrolet", "Ford", "Hyundai", "Nissan", "Land Rover", "Changan", "Peugeot"],
      avgSellingPriceSar: 95000,
      financeAvailable: "unknown",
      vehicleType: "used_only",
    },
  },
  {
    sdId: "S0111",
    nameEn: "Rawdat Al Khair Cars",
    nameAr: "معرض روضة الخير للسيارات",
    pos: { eastM: -340.0, northM: 78.3 },
    street: "Ibn Sayyidah",
    mapsUrl: "https://www.google.com/maps?q=24.5486293,46.6785375",
    note: "Al Shifa walk 20 Sep 2026. GPS pin resolved from Google Places (exact name match) — confirm on site.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 65,
      inventoryInside: 60,
      inventoryOutside: 5,
      inventoryAgePctOver5: 60,
      showroomSizeSqm: 1000,
      mainBrands: ["Toyota", "Lexus", "Mercedes", "Porsche", "Hyundai"],
      avgSellingPriceSar: 70000,
      financeAvailable: "unknown",
      vehicleType: "used_only",
    },
  },
  {
    sdId: "S0112",
    nameEn: "Ramz Al Riyadh",
    nameAr: "رمز الرياض",
    pos: { eastM: 1030.0, northM: 15.0 },
    street: "Al Shifa strip",
    note: "Al Shifa walk 20 Sep 2026. NO GPS — coordinate is the surveyor's nearby placeholder, not a real pin. Needs a tap on site.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 75,
      inventoryAgePctOver5: 15,
      showroomSizeSqm: 1400,
      mainBrands: [],
      avgSellingPriceSar: 60000,
      financeAvailable: "unknown",
      vehicleType: "used_only",
    },
  },
  {
    sdId: "S0113",
    nameEn: "Al Qahtani Group Cars - Al Shifa",
    nameAr: "مجموعة القحطاني للسيارات حي الشفا",
    pos: { eastM: -103.5, northM: 273.3 },
    street: "Abi Al Ala Al Najmi",
    mapsUrl: "https://www.google.com/maps?q=24.5503812,46.6808729",
    note: "Al Shifa walk 20 Sep 2026. GPS pin resolved from Google Places (exact name match) — confirm on site.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 65,
      inventoryAgePctOver5: 5,
      showroomSizeSqm: 1000,
      mainBrands: [],
      avgSellingPriceSar: 90000,
      financeAvailable: "unknown",
      vehicleType: "new_only",
    },
  },
];
