import type { ShifaSeedIn } from "./shifa-walk-sep20-types";

/** 20 Sep 2026 Al Shifa walk — part C (S0114–S0121).
 *
 * Eight showrooms on Ali Ibn Asad / Abi Abdullah Al Jilani, a street east of the
 * main Ibn Sayyidah strip. They were initially mistaken for duplicates of existing
 * census pins because their placeholder coordinates fell near unrelated dealers on
 * the main strip. Confirmed as new showrooms by the surveyor.
 *
 * 6 of 8 carry Google Places pins; S0118 and S0121 keep the surveyor's placeholder
 * coordinate and still need an on-site tap. See each record's note.
 */
export const SHIFA_WALK_SEP20_C: ShifaSeedIn[] = [
  {
    sdId: "S0114",
    nameEn: "Al Wisham Al Jadeed",
    nameAr: "الوشام الجديد",
    pos: { eastM: 314.5, northM: 0.6 },
    street: "Ali Ibn Asad",
    mapsUrl: "https://www.google.com/maps?q=24.5479314,46.6850019",
    note: "Al Shifa walk 20 Sep 2026. GPS pin resolved from Google Places (exact name match), confirmed against field screenshot of Ali Ibn Asad street.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 45,
      inventoryAgePctOver5: 20,
      showroomSizeSqm: 700,
      mainBrands: ["Cadillac", "GMC", "BMW", "Ford", "Chevrolet", "Toyota", "Mercedes"],
      avgSellingPriceSar: 150000,
      financeAvailable: "unknown",
      vehicleType: "used_only",
    },
  },
  {
    sdId: "S0115",
    nameEn: "Salim Cars",
    nameAr: "معرض سليم للسيارات",
    pos: { eastM: 384.5, northM: 21.0 },
    street: "Al Khalil Ibn Ahmad / Ali Ibn Asad",
    mapsUrl: "https://www.google.com/maps?q=24.5481145,46.6856931",
    note: "Al Shifa walk 20 Sep 2026. GPS pin resolved from Google Places (exact name match).",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 50,
      inventoryAgePctOver5: 15,
      showroomSizeSqm: 600,
      mainBrands: ["Ford", "Mazda", "Toyota", "Kia", "Hyundai"],
      avgSellingPriceSar: 90000,
      financeAvailable: "unknown",
      vehicleType: "mix",
    },
  },
  {
    sdId: "S0116",
    nameEn: "Lamset Al Mustaqbal Cars",
    nameAr: "معرض لمسة المستقبل للسيارات",
    pos: { eastM: 227.5, northM: -150.6 },
    street: "Abi Abdullah Al Jilani",
    mapsUrl: "https://www.google.com/maps?q=24.546573,46.6841423",
    note: "Al Shifa walk 20 Sep 2026. GPS pin resolved from Google Places (exact name match). Listing is categorised as a parking lot - VERIFY it trades as a showroom.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 35,
      inventoryInside: 22,
      inventoryOutside: 4,
      inventoryAgePctOver5: 35,
      showroomSizeSqm: 500,
      mainBrands: ["Hyundai", "Geely", "Toyota"],
      avgSellingPriceSar: 60000,
      financeAvailable: "unknown",
      vehicleType: "used_only",
    },
  },
  {
    sdId: "S0117",
    nameEn: "Asdaa Cars Al Shifa",
    nameAr: "معرض أصداء السيارات الشفاء",
    pos: { eastM: -280.3, northM: 166.4 },
    street: "Ibn Sayyidah",
    mapsUrl: "https://www.google.com/maps?q=24.5494211,46.6791272",
    note: "Al Shifa walk 20 Sep 2026. GPS pin resolved from Google Places (exact name match).",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 65,
      inventoryAgePctOver5: 0,
      showroomSizeSqm: 800,
      mainBrands: ["Hyundai", "Kia"],
      avgSellingPriceSar: 90000,
      financeAvailable: "unknown",
      vehicleType: "new_only",
    },
  },
  {
    sdId: "S0118",
    nameEn: "Turo 1 Cars",
    nameAr: "تورو 1 للسيارات",
    pos: { eastM: 580.0, northM: 15.0 },
    street: "Al Shifa (unconfirmed)",
    note: "Al Shifa walk 20 Sep 2026. NO GPS - no Google listing found. Coordinate is the surveyor's nearby placeholder. Needs a tap on site.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 45,
      inventoryAgePctOver5: 15,
      showroomSizeSqm: 800,
      mainBrands: ["Kia", "Mazda", "Jetour"],
      avgSellingPriceSar: 75000,
      financeAvailable: "unknown",
      vehicleType: "used_only",
    },
  },
  {
    sdId: "S0119",
    nameEn: "Al Hawadij Commercial Services",
    nameAr: "الهوادج الخدمات التجارية",
    pos: { eastM: 336.3, northM: 14.0 },
    street: "Ali Ibn Asad",
    mapsUrl: "https://www.google.com/maps?q=24.5480515,46.6852168",
    note: "Al Shifa walk 20 Sep 2026. GPS pin resolved from Google Places (exact name match), confirmed against field screenshot. Listed as a car rental agency - VERIFY vehicle sales activity.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 40,
      inventoryAgePctOver5: 20,
      showroomSizeSqm: 600,
      mainBrands: ["Kia", "Toyota", "Hyundai"],
      avgSellingPriceSar: 70000,
      financeAvailable: "unknown",
      vehicleType: "used_only",
    },
  },
  {
    sdId: "S0120",
    nameEn: "Al Ezz Cruise Cars",
    nameAr: "معرض العزكروز للسيارات",
    pos: { eastM: 271.9, northM: -46.8 },
    street: "Abi Abdullah Al Jilani",
    mapsUrl: "https://www.google.com/maps?q=24.5475059,46.6845808",
    note: "Al Shifa walk 20 Sep 2026. GPS pin resolved from Google Places (exact name match); pin supplied by the surveyor.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 35,
      inventoryInside: 14,
      inventoryOutside: 4,
      inventoryAgePctOver5: 0,
      showroomSizeSqm: 500,
      mainBrands: ["Toyota", "GMC", "Lexus", "Land Rover", "Jetour"],
      avgSellingPriceSar: 150000,
      financeAvailable: "unknown",
      vehicleType: "used_only",
    },
  },
  {
    sdId: "S0121",
    nameEn: "Sama Al Shifa Al Hadith",
    nameAr: "معرض سماء الشفاء الحديث",
    pos: { eastM: 263.7, northM: -2.9 },
    street: "Al Shifa (unconfirmed)",
    note: "Al Shifa walk 20 Sep 2026. NO GPS - no Google listing found. Coordinate is the surveyor's nearby placeholder. Needs a tap on site.",
    walked: {
      visitDate: "2026-09-20",
      inventoryUnits: 30,
      inventoryInside: 24,
      inventoryOutside: 6,
      inventoryAgePctOver5: 25,
      showroomSizeSqm: 800,
      mainBrands: ["Toyota", "Nissan", "Mazda", "Kia", "Hyundai"],
      avgSellingPriceSar: 74000,
      financeAvailable: "unknown",
      vehicleType: "used_only",
    },
  },
];
