/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CeoRouteImport } from './routes/ceo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DeepdiveRouteImport } from './routes/deepdive'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as DossierIdRouteImport } from './routes/dossier.$id'
import { Route as SurveyIdRouteImport } from './routes/survey.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CeoRoute = CeoRouteImport.update({
  id: '/ceo',
  path: '/ceo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeepdiveRoute = DeepdiveRouteImport.update({
  id: '/deepdive',
  path: '/deepdive',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const DossierIdRoute = DossierIdRouteImport.update({
  id: '/dossier/$id',
  path: '/dossier/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyIdRoute = SurveyIdRouteImport.update({
  id: '/survey/$id',
  path: '/survey/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ceo': typeof CeoRoute
  '/dashboard': typeof DashboardRoute
  '/deepdive': typeof DeepdiveRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRoute
  '/research': typeof ResearchRoute
  '/dossier/$id': typeof DossierIdRoute
  '/survey/$id': typeof SurveyIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ceo': typeof CeoRoute
  '/dashboard': typeof DashboardRoute
  '/deepdive': typeof DeepdiveRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRoute
  '/research': typeof ResearchRoute
  '/dossier/$id': typeof DossierIdRoute
  '/survey/$id': typeof SurveyIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ceo': typeof CeoRoute
  '/dashboard': typeof DashboardRoute
  '/deepdive': typeof DeepdiveRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRoute
  '/research': typeof ResearchRoute
  '/dossier/$id': typeof DossierIdRoute
  '/survey/$id': typeof SurveyIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ceo'
    | '/dashboard'
    | '/deepdive'
    | '/login'
    | '/ops'
    | '/research'
    | '/dossier/$id'
    | '/survey/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ceo'
    | '/dashboard'
    | '/deepdive'
    | '/login'
    | '/ops'
    | '/research'
    | '/dossier/$id'
    | '/survey/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/ceo'
    | '/dashboard'
    | '/deepdive'
    | '/login'
    | '/ops'
    | '/research'
    | '/dossier/$id'
    | '/survey/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CeoRoute: typeof CeoRoute
  DashboardRoute: typeof DashboardRoute
  DeepdiveRoute: typeof DeepdiveRoute
  LoginRoute: typeof LoginRoute
  OpsRoute: typeof OpsRoute
  ResearchRoute: typeof ResearchRoute
  DossierIdRoute: typeof DossierIdRoute
  SurveyIdRoute: typeof SurveyIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceo': {
      id: '/ceo'
      path: '/ceo'
      fullPath: '/ceo'
      preLoaderRoute: typeof CeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deepdive': {
      id: '/deepdive'
      path: '/deepdive'
      fullPath: '/deepdive'
      preLoaderRoute: typeof DeepdiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossier/$id': {
      id: '/dossier/$id'
      path: '/dossier/$id'
      fullPath: '/dossier/$id'
      preLoaderRoute: typeof DossierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey/$id': {
      id: '/survey/$id'
      path: '/survey/$id'
      fullPath: '/survey/$id'
      preLoaderRoute: typeof SurveyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CeoRoute: CeoRoute,
  DashboardRoute: DashboardRoute,
  DeepdiveRoute: DeepdiveRoute,
  LoginRoute: LoginRoute,
  OpsRoute: OpsRoute,
  ResearchRoute: ResearchRoute,
  DossierIdRoute: DossierIdRoute,
  SurveyIdRoute: SurveyIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
